- example/index.html
- package.json
- src/basic_message.ts
- src/basic_message_enricher.ts
- src/chat_manager.ts
- src/current_user.ts
- src/fetched_attachment.ts
- src/file_resource.ts
- src/global_user_store.ts
- src/message.ts
- src/payload_deserializer.ts
- src/presence_subscription.ts
- src/room_store.ts
- src/room_subscription.ts
- src/user_subscription.ts
- src/utils.ts
- tslint.json
- yarn.lock
Add support for message attachments 
Also includes a few other pusher-platform-js related updates and logging tweaks
> Attachments support

- src/current_user.ts
> Make sure query params are added to fetchRoomMessages request

- CHANGELOG.md
- src/constants.ts
- src/current_user.ts
- src/user_subscription.ts
mimir: https://github.com/pusher/mimir/pull/240
> Experimental typing indicator debouncing

- src/current_user.ts
Validates if the `position` is actually a number.
> Fix set cursor

- src/chat-manager.js
- src/current-user.js
> Use the presence service for presence-related things

- example/index.html
- example/main.js
- example/style.css
this is pretty much just the existing example, updated to use the new interfaces, and with some changes to fix stuff that was broken in firefox (haven't tested in any other browsers). Long term we probably want to make sure this works in all major browsers and in standards mode (at the moment it's relying on quirks mode, but I can't immediately figure out why...)
> minimal changes to get existing example working in firefox

- example/index.html
- src/token-provider.js
> only make a single token provider request at a time

- example/main.js
- src/current-user.js
- src/message-subscription.js
- src/presence-subscription.js
- src/typing-indicators.js
- src/user-subscription.js
- tests/main.js
open to discussion on all these. Changes suggested by booker.
- `addUser` -> `addUserToRoom`; `removeUser` -> `removeUserFromRoom`
- have all functions receive a single options object for consistency, named parameters, etc. It's a nice pattern we were already using a lot -- should use it everywhere :)
- append 'on' to all the hooks: `onNewMessage`, `onUserStartedTyping` etc. Convention in JS land? needn't necessarily be the same in other SDKs (since we should follow the conventions of the ecosystem)
optimistic mimir update: https://github.com/pusher/mimir/pull/290/commits/8fde328d3e283702555771a8d2771809636ee03b
> Vanilla consistency

- package.json
- rollup/react-native.js
- rollup/shared.js
- rollup/web.js
- yarn.lock
> react native build

- src/current-user.js
- tests/main.js
> remove getAllRooms

- src/constants.js
- src/current-user.js
Collect `setReadCursor` requsts in a buffer, if `setReadCursor` is called many times in a short period, just respect the call with the greatest `position`.
Resolves/rejects all promises when the buffered requset is made, so the interface is identical.
> buffer set read cursor requests

- src/chat-manager.js
- src/current-user.js
- src/cursor-subscription.js
- src/message-subscription.js
- src/presence-subscription.js
- src/room-subscription.js
- src/typing-indicators.js
- src/user-subscription.js
Makes the treatment of hooks more consistent throughout, by keeping them all in one object rather than passing them around. Precursor to some v2 refactoring.
> collect all hooks in one object

- CHANGELOG.md
- src/current-user.js
- src/cursor-store.js
- src/cursor-subscription.js
- src/membership-subscription.js
- src/message-subscription.js
- src/room-store.js
- src/room-subscription.js
- src/room.js
- src/user-presence-subscription.js
- src/user-store.js
- src/user-subscription.js
- tests/main.js
Room memberships (the user property on rooms) are now available only after subscribing to a room. Attempting to access them before subscribing will throw an error.
> make membership subscription when subscribing to room

- CHANGELOG.md
- example/main.js
- package.json
- src/membership-subscription.js
- src/store.js
- src/user-presence-subscription.js
- src/user.js
- tests/main.js
- yarn.lock
> Api v2 on online state changed

- src/chat-manager.js
- src/current-user.js
- src/cursor-store.js
- src/membership-subscription.js
- src/message-subscription.js
- src/room-store.js
- src/typing-indicators.js
- tests/main.js
We won't know for sure that this is all the required changes until we can run the tests against the updated API.
> treat room IDs as strings everywhere

- CHANGELOG.md
- example/main.js
- src/current-user.js
- src/parsers.js
- src/utils.js
- tests/main.js
We never require it any more so this is just dead code.
> remove fetchAttachment and friends

- CHANGELOG.md
- src/current-user.js
- src/parsers.js
- src/room-store.js
- src/room.js
- tests/main.js
> support customData on the room object

- src/current-user.js
- src/parsers.js
- tests/main.js
Pending server side change.
mimir: https://github.com/pusher/mimir/pull/501
> attachment name

- src/current-user.js
- src/user-subscription.js
Optimistically pop the room before we try to leave it to avoid the race condition. Put it back in if the request to leave fails.
> don't pop room on leave, wait for user subscription event

- src/chat-manager.js
- src/current-user.js
- src/room-subscription.js
- tests/integration/main.js
Starting out by implementing new methods since it's easier, we can decide if we want to combine their behaviour and switch on the shape of the input after we've implemented attachment support so that we know exactly what that will look like.
> sendMultipartMessage and sendSimpleMessage for inline message parts only

- src/attachment.js
- src/current-user.js
- src/message-subscription.js
- src/message.js
- src/parsers.js
- src/room-subscription.js
- tests/integration/main.js
builds on #142 we probably ought to make a v3 branch to merge this stuff in to
> V3 subscribe to room

- src/current-user.js
- tests/integration/main.js
Since the message parser understands v3 messages already there's not much to do here. Mostly more tests.
> fetchMultipartMessages

- package.json
- src/chat-manager.js
- src/current-user.js
- src/message-subscription.js
- src/message.js
- src/parsers.js
- src/room-subscription.js
- tests/integration/main.js
- yarn.lock
Introduces the `message_deleted` event and adds the `onMessageDeleted` hook.
Note that the build won't pass till we have one of the server PR's merged in since there's a small bug in the V5 handler.
> Message deleted event

- .gitignore
- .travis.yml
- example/service-worker.js
- package.json
- script/puppeteer-run.js
- tests/integration/main.js
- tests/jest/chatmanager.js
- tests/jest/cursors.js
- tests/jest/helpers/config/example.js
- tests/jest/helpers/main.js
- tests/jest/messages.js
- tests/jest/presence.js
- tests/jest/rooms.js
- yarn.lock
Ports the most basic tests to the new jest-pupeteer setup
> Use Pupeteer and Jest for integration tests

- package.json
- src/batch.js
- src/constants.js
- src/current-user.js
- src/cursor-store.js
- src/message-subscription.js
- src/room-store.js
- src/user-store.js
- tests/unit/batch.js
Collect fetch missing user requests and fire them off at most every 100ms.
> Lazily batch fetching of missing users

- src/current-user.js
- src/room-subscription.js
- tests/integration/main.js
Provide a `disableCursors` option to `subscribeRoom` and `subscribeRoomMultipart`, and throw an appropriate error if you try and get cursors for a room with with a disabled cursors subscription.
> provide option to disable cursors on subscription

- CHANGELOG.md
- src/current-user.js
V2 does not send message events. Adding a warning to customers can know what to expect
> Log warning if `onMessageDeleted` hook passed to `subscribeToRoom`

- src/token-provider.js
- src/utils.js
> Passing functions as values for url, query params or headers to Token Provider.
