src/current_user.ts
src/room_delegate.ts

@hamchapman I saw there were a load of comments about how we might want to do error handling going forward... so this isn't necessarily a permanent solution, but at least makes it possible to find out if there is an error opening a subscription (which currently is a silent failure)

add error listener to subscriptions so we can catch if there is an error subscribing

---

CHANGELOG.md
src/chat_manager.ts
src/current_user.ts
src/cursor_subscription.ts
src/cursor_types.ts
src/token_provider.ts

The basic flow works here. Gets cursors and makes user subscription simultaneously, and then call `onSuccess` with a `currentUser` object that has been augmented with a `cursors` property. The interface probably needs some work though, I'm currently passing `userId` in to `ChatManager` so that I have access to it to  make the GET request to cursors, I do think the request should be done at this point, because having access to your cursors can block handling messages on a room subscription if you want to know which one's you've already seen.
Also, do we need to polyfill promises / use explicit callbacks, or does typescript do that for you?

Get own cursors on connection

---

src/current_user.ts

The default for message limit is 20 anyway and is set server side. So not passing it in will have the same effect.
This also makes the argument be of `number` type. Previously anyone could pass anything and we didn't have checks either.

Make message limit optional

---

CHANGELOG.md
src/chat_manager.ts
src/current_user.ts

Throws an error if the consumer fails to provide a `userId` to the `ChatManager` constructor. Also fixes a load of build and lint errors that were in master. Gotta remember to `yarn build && yarn lint && yarn format`! 😉

Error on missing user

---

src/chat_manager.ts

fix for #25 
Catch block wasn't added to the promise chain until after it had already been invoked, leading to any errors being thrown to the console.

catch error parsing cursors request earlier

---

.gitignore
src/chat-manager.js
src/current-user.js
src/cursor-store.js
src/cursor-subscription.js
src/cursor.js
src/message-subscription.js
src/parsers.js
src/presence-subscription.js
src/user-store.js
src/user-subscription.js
src/user.js
tests/main.js

~depends on https://github.com/pusher/chatkit-cursors/pull/13 being merged and deployed (but can be reviewed in the meantime as the above is deployed on deneb)~ done!
interface:
```javascript
currentUser.setReadCursor(roomId, position)
currentUser.readCursor(roomId) // own cursors (sync)
currentUser.readCursor(roomId, userId) // other user's cursors (after subscribing to the room) (sync)
```
`newReadCursor` hook on both the user sub (gets changes to own cursors) and the room sub (gets changes to other's cursors)

Vanilla cursors

---

src/current-user.js
src/cursor-subscription.js
src/message-subscription.js
src/presence-subscription.js
src/room-subscription.js
src/user-subscription.js
tests/main.js

All subs can now be cancelled with `sub.cancel()`. e.g.
```
currentUser.roomSubscriptions[roomId].cancel()
```
corresponding docs update: https://github.com/pusher/mimir/pull/290/commits/b35eade9de4771ef66a6ab1fb1320c692ec284cd

Vanilla cancellation

---

package.json
tests/main.js
yarn.lock

Bump pusher-platform dependency to 0.15.0 and unskip previously skipped tests

---

src/token-provider.js
src/user-store.js
src/utils.js

Slightly changes the interface to put `queryParams` and `headers` as separate options in the root options object. Open to debate on this but not sure the extra nesting is really worth it?
```javascript
const tokenProvider = new TokenProvider({
url: 'my-token-provider/token',
queryParams: {
custom: 'parameters'
},
headers: {
custom: 'headers'
}
})
```
corresponding mimir change: https://github.com/pusher/mimir/pull/290/commits/c4d095cc8133b6860096d7e3a27d91216acc11da

Vanilla auth context

---

src/room-store.js

If we're popping a room from the store, then we don't want it anyway, so there's no sense in fetching it.
This was the cause of `room_membership_required` errors when leaving a room.
- `leaveRoom` pops the room from the store
- the `removed_from_room` event is received and causes a second pop of the same room
- this room is no longer in the store, so we try to fetch it (we shouldn't bother)
- the API returns a 401 because we no longer have permission to get info about the room (since we're not a member of it any more)

don't fetch on pop if we don't have a local copy of a room

---

src/user.js

Makes the object consistent so that consumers don't have to check for undefined. It would be nice if we always had the appropriate data from the API, but this is a "better than nothing" fix in the meantime.

sensible default for missing presence in user's presence property

---

src/token-provider.js
src/user-store.js

- always use the batch endpoint
- keep references to ongoing requests
- only make new requests for user IDs that don't already have an ongoing request

track ongoing user info requests so we don't make redundant requests

---

src/chat-manager.js
src/current-user.js
src/message-subscription.js
src/typing-indicators.js
src/user-subscription.js

Consumes typing indicators on the messages sub, publishes them to the v2 route. Might want to review https://github.com/pusher/chatkit-client-js/pull/76 first in isolation (makes these changes fairly trivial).

Api v2 typing indicators

---

src/chat-manager.js
src/current-user.js
src/membership-subscription.js
src/parsers.js
src/room.js
src/user-subscription.js

Create membership subscriptions to handle member joined and left events.
- subscribes to the membership sub for every room on connection (before initializing user store, so we can still use the initial membership data to pre-fetch user info)
- subscribes to the membership sub for new rooms as they are joined (or you're added)
- unsubscribes from membership subs when rooms are left (or you're removed)

Api v2 membership subscriptions

---

src/current-user.js
src/message-subscription.js
src/typing-indicators.js

In `v2` the server won't be filtering out the connected user's own typing indicators, so we need to filter them client side. This is a trivial check against the ID.

don't fire onIsTyping for the user's own typing indicators

---

CHANGELOG.md
src/chat-manager.js
src/current-user.js
tests/main.js

This PR adds a `disconnect` method to the `ChatManager` class to allow for easy disconnection from Chatkit. It cancels all subscriptions on the `CurrentUser` object.

Add disconnect

---

CHANGELOG.md
src/current-user.js
tests/main.js

It was always being shown as "unknown", as we explicitly did not
subscribe to it. But it's useful to be able to treat the current user
the same as any other when listing them.

Subscribe to own presence state

---

src/parsers.js

This will be `undefined` when the room hasn't been deleted (but the key will always exist).

room.deletedAt

---

src/current-user.js
src/room-subscription.js
tests/integration/main.js

Trying to reproduce #140 uncovered a couple of related issues.
- If two room subscriptions are on the go at once, it is possible to connect as the same one twice (since we access the room subscription from the global state). The platform library allows this, and will register your event handlers twice. Fixed by using a local reference to the subscription so that it can't change beneath us.
- Again, if two room subscriptions are made in very quick succession. The first one might be cancelled before it is connected, but the cancellation will then do nothing, and the connection will go ahead as normal, leading to the new and old connection both surviving. Fixed by denying an attempt to connect a cancelled subscription.

Subscribe to room race

---

src/current-user.js
src/membership-subscription.js
src/message-subscription.js
src/reconnection-handlers.js
src/room-subscription.js
tests/unit/membership-sub-reconnection.js

Wait for all three components of the room subscription to be established before emitting events from any of them so we have all the information we need. Change involves passing events up to the RoomSubscription so that it can coordinate where before each component called the top-level hooks directly.

Buffer room events

---

src/token-provider.js
yarn.lock

Depends on https://github.com/pusher/pusher-platform-js/pull/96/files
TODO:

Add `withCredentials` options to the token provider

---

src/current-user.js
tests/integration/main.js

We rely on it later on, so we should check it exists (mostly relevant for react native).

check part.file.size

---

tests/integration/main.js

Firefox does not allow slashes in filenames. It is still possible to use slashes, and there are tests for this on the server side.

Make tests compatible with Firefox

---

package.json
yarn.lock

```
CVE-2019-10744 More information
high severity
Vulnerable versions: < 4.17.13
Patched version: 4.17.13
Affected versions of lodash are vulnerable to Prototype Pollution.
The function defaultsDeep could be tricked into adding or modifying properties of Object.prototype using a constructor payload.
```
For more on how `resolutions` work refer to: https://yarnpkg.com/lang/en/docs/selective-version-resolutions/

Ensure that we're using atleast lodash 4.17.13

---

src/chat-manager.js
src/current-user.js
src/notification-subscription.js
src/notification.js

Subscribes to the online notification subscription on the push_notifications service and displays notifications received if the tab is hidden. Focusses the tab on click and provides an optional `onClick` hook that receives the room ID so that the application can focus the correct room.
Only enabled if push notifications proper are enabled. We might want to provide an option to enable this independently in the future. This has been manually tested, but we will be writing automated tests for it with the new framework.

Online notifications

---

CHANGELOG.md
package.json
yarn.lock

Currently, if you pass a service worker registration with an invalid scope when enabling notifications, the SDK fails silently.
This Beams SDK version returns a descriptive error instead: https://github.com/pusher/push-notifications-web/commit/25a1a6a7b60e7e2feec65bd98aa3eb3d44026a9e#diff-ecdae514d2d75de322aae0d24a1a6c48R93

Bump Beams SDK version to get better error messages
